# Generated by Django 5.2.1 on 2025-07-31 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bati", "insert_nomenclature"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="demandetravaux",
            options={"ordering": ["-date_demande_permis"]},
        ),
        migrations.AlterModelOptions(
            name="travaux",
            options={"ordering": ["-date"]},
        ),
    ]
