# Generated by Django 5.2.1 on 2025-06-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', 'insert_nomenclature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bati',
            name='remarque_generale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bati',
            name='risques_nat',
            field=models.ManyToManyField(blank=True, limit_choices_to={'id_type__code': 'RISQUE'}, related_name='batiments_risquenat', to='bati.nomenclature'),
        ),
    ]
