# Generated by Django 5.2.1 on 2025-06-26 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', 'insert_nomenclature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondoeuvre',
            name='type',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__code': 'SO'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structure_second_oeuvre', to='bati.nomenclature', verbose_name='Type de second oeuvre'),
        ),
    ]
