# Generated by Django 5.2.5 on 2025-08-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bati", "insert_nomenclature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bati",
            name="ancien_index",
        ),
        migrations.RemoveField(
            model_name="bati",
            name="denivelle",
        ),
        migrations.AlterField(
            model_name="bati",
            name="perspectives",
            field=models.ManyToManyField(
                limit_choices_to={"id_type__code": "PERSP"},
                through="bati.Perspective",
                to="bati.nomenclature",
            ),
        ),
    ]
