# Generated by Django 5.2.1 on 2025-06-26 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bati", "insert_nomenclature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travaux",
            name="date",
            field=models.DateField(
                db_comment="Ce champs est non null depuis la v2, remplie avec 1800-01-01 quand l'info était absente"
            ),
        ),
        migrations.CreateModel(
            name="MateriauxFinFinitionStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "finition",
                    models.ForeignKey(
                        limit_choices_to={"id_type__code": "FIN"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finition_mat_fin_rel",
                        to="bati.nomenclature",
                        verbose_name="Finition",
                    ),
                ),
                (
                    "materiaux_fin",
                    models.ForeignKey(
                        limit_choices_to={"id_type__code": "MAT_FIN"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiaux_fin_rel",
                        to="bati.nomenclature",
                        verbose_name="Materiaux fin",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finitions",
                        to="bati.structure",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="structure",
            name="materiaux_fin",
            field=models.ManyToManyField(
                through="bati.MateriauxFinFinitionStructure",
                through_fields=["structure", "materiaux_fin"],
                to="bati.nomenclature",
            ),
        ),
    ]
