# Generated by Django 5.2.1 on 2025-07-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bati", "insert_nomenclature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="illustration",
            name="fichier_src",
            field=models.ImageField(
                upload_to="post_images/", verbose_name="fichier source"
            ),
        ),
    ]
