# Generated by Django 5.2.1 on 2025-06-20 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bati", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeTravaux",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("demande_dep", models.BooleanField(default=False)),
                ("autorisation_p", models.BooleanField(default=False, null=True)),
                ("date_permis", models.DateField(null=True)),
                ("date_demande_permis", models.DateField(null=True)),
                ("num_permis", models.CharField()),
                (
                    "bati",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_travaux",
                        to="bati.bati",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Travaux",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("autorisation", models.BooleanField(null=True)),
                ("subvention_pne", models.IntegerField(null=True)),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travaux",
                        to="bati.demandetravaux",
                    ),
                ),
                (
                    "nature",
                    models.ForeignKey(
                        limit_choices_to={"id_type__code": "NATURE_TRAVAUX"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nature_travaux",
                        to="bati.nomenclature",
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        limit_choices_to={"id_type__code": "USAGE_TRAVAUX"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_travaux",
                        to="bati.nomenclature",
                    ),
                ),
            ],
        ),
    ]
