# Generated by Django 5.2.1 on 2025-06-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomenclature',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nomenclaturetype',
            options={'managed': False},
        ),
    ]
