# Generated by Django 5.2.1 on 2025-10-22 14:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bati", "0001_remove_bati_ancien_index_remove_bati_denivelle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandetravaux",
            name="remarque",
            field=models.TextField(blank=True, null=True, verbose_name="Remarque"),
        ),
        migrations.AlterField(
            model_name="bati",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name="bati",
            name="masques",
            field=models.ManyToManyField(
                blank=True,
                help_text="Element(s) masquant le batiment",
                limit_choices_to={"id_type__code": "MASQUE"},
                null=True,
                related_name="batiments_info_masque",
                to="bati.nomenclature",
            ),
        ),
        migrations.AlterField(
            model_name="bati",
            name="notepatri",
            field=models.ForeignKey(
                limit_choices_to={"id_type__code": "NOTE_PAT"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batiments_notepatri",
                to="bati.nomenclature",
                verbose_name="Note patrimoniale",
            ),
        ),
        migrations.AlterField(
            model_name="bati",
            name="type_bat",
            field=models.ForeignKey(
                limit_choices_to={"id_type__code": "TYPE_BAT"},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="batiments_type",
                to="bati.nomenclature",
                verbose_name="Type de batiment",
            ),
        ),
        migrations.AlterField(
            model_name="demandetravaux",
            name="autorisation_p",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Autorisation accordée ?"
            ),
        ),
        migrations.AlterField(
            model_name="demandetravaux",
            name="demande_dep",
            field=models.BooleanField(
                default=False, verbose_name="Demande déja déposée ?"
            ),
        ),
        migrations.AlterField(
            model_name="demandetravaux",
            name="num_permis",
            field=models.CharField(
                blank=True, null=True, verbose_name="Numéro de permis"
            ),
        ),
    ]
