# Generated by Django 5.2.1 on 2025-06-26 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bati", "0001_alter_travaux_date_materiauxfinfinitionstructure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secondoeuvre",
            name="type",
            field=models.ForeignKey(
                limit_choices_to={"id_type__code": "SO"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="structure_second_oeuvre",
                to="bati.nomenclature",
                verbose_name="Type de second oeuvre",
            ),
        ),
        migrations.CreateModel(
            name="MateriauxFinFinitionSecondOeuvre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "finition",
                    models.ForeignKey(
                        limit_choices_to={"id_type__code": "FIN"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finition_mat_fin_rel_soc",
                        to="bati.nomenclature",
                        verbose_name="Finition",
                    ),
                ),
                (
                    "materiaux_fin",
                    models.ForeignKey(
                        limit_choices_to={"id_type__code": "MAT_FIN"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiaux_fin_rel_sec",
                        to="bati.nomenclature",
                        verbose_name="Materiaux fins",
                    ),
                ),
                (
                    "second_oeuvre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_oeuvre",
                        to="bati.secondoeuvre",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="secondoeuvre",
            name="materiaux_fin",
            field=models.ManyToManyField(
                through="bati.MateriauxFinFinitionSecondOeuvre",
                through_fields=["second_oeuvre", "materiaux_fin"],
                to="bati.nomenclature",
            ),
        ),
    ]
