# Generated by Django 5.2.1 on 2025-07-10 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bati", "0001_alter_illustration_fichier_src"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secondoeuvre",
            name="conservation",
            field=models.ForeignKey(
                limit_choices_to={"id_type__code": "CONSERVATION"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="second_oeuvre_conservation",
                to="bati.nomenclature",
                verbose_name="Etat de conservation",
            ),
        ),
    ]
