# Generated by Django 5.2.1 on 2025-06-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='parentId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
