# Generated by Django 5.2.1 on 2025-07-11 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bati", "0002_alter_secondoeuvre_conservation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClasseArchiNature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        limit_choices_to={"id_type__code": "CL_ARCHI"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classe_archi_nature",
                        to="bati.nomenclature",
                    ),
                ),
                (
                    "nature",
                    models.ForeignKey(
                        limit_choices_to={"id_type__code": "NATURE_TRAVAUX"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nature_classe_archi",
                        to="bati.nomenclature",
                    ),
                ),
            ],
        ),
    ]
