# Generated by Django 5.2.1 on 2025-06-24 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bati", "0002_nomenclature_parentid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perspective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                (
                    "bati",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bati.bati"
                    ),
                ),
                (
                    "perspective",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"id_type__code": "PERSPECTIVE"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perspective_bati",
                        to="bati.nomenclature",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bati",
            name="perspectives",
            field=models.ManyToManyField(
                through="bati.Perspective", to="bati.nomenclature"
            ),
        ),
    ]
