# Generated by Django 5.2.1 on 2025-06-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0002_alter_nomenclature_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nomenclature',
            table='ref_nomenclatures"."t_nomenclatures',
        ),
        migrations.AlterModelTable(
            name='nomenclaturetype',
            table='ref_nomenclatures"."bib_nomenclatures_types',
        ),
    ]
