# Generated by Django 5.2.1 on 2025-10-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bati", "0002_demandetravaux_remarque_alter_bati_geom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandetravaux",
            name="date_demande_permis",
            field=models.DateField(help_text="Au format JJ/MM/AAA", null=True),
        ),
        migrations.AlterField(
            model_name="demandetravaux",
            name="date_permis",
            field=models.DateField(help_text="Au format JJ/MM/AAA", null=True),
        ),
        migrations.AlterField(
            model_name="perspective",
            name="date",
            field=models.DateField(help_text="Au format JJ/MM/AAA", null=True),
        ),
        migrations.AlterField(
            model_name="travaux",
            name="date",
            field=models.DateField(
                db_comment="Ce champs est non null depuis la v2, remplie avec 1800-01-01 quand l'info était absente",
                help_text="Au format JJ/MM/AAA",
            ),
        ),
    ]
