# Generated by Django 5.2.1 on 2025-06-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bati", "0003_perspective_bati_perspectives"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bati",
            name="masques",
        ),
        migrations.AddField(
            model_name="bati",
            name="masques",
            field=models.ManyToManyField(
                limit_choices_to={"id_type__code": "MASQUE"},
                related_name="batiments_info_masque",
                to="bati.nomenclature",
            ),
        ),
    ]
