# Generated by Django 5.2.1 on 2025-07-11 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bati", "0003_classearchinature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classearchinature",
            name="classe",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"id_type__code": "CL_ARCHI"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classe_archi_nature",
                to="bati.nomenclature",
            ),
        ),
        migrations.AlterField(
            model_name="classearchinature",
            name="nature",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"id_type__code": "NATURE_TRAVAUX"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nature_classe_archi",
                to="bati.nomenclature",
            ),
        ),
    ]
