# Generated by Django 5.2.7 on 2025-10-23 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bati", "0003_alter_demandetravaux_date_demande_permis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bati",
            name="periode_utilisation",
            field=models.CharField(
                blank=True,
                null=True,
                verbose_name="Periode approxmiative d'utilisation",
            ),
        ),
        migrations.AddField(
            model_name="bati",
            name="surface",
            field=models.IntegerField(
                blank=True, help_text="Surface en m²", null=True, verbose_name="Surface"
            ),
        ),
        migrations.AddField(
            model_name="bati",
            name="type_prioprietaire",
            field=models.ForeignKey(
                limit_choices_to={"id_type__code": "TYPE_PROPRIO"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_proprietaire",
                to="bati.nomenclature",
                verbose_name="Type de propriétaire",
            ),
        ),
        migrations.AlterField(
            model_name="bati",
            name="classe",
            field=models.ForeignKey(
                limit_choices_to={"id_type__code": "CL_ARCHI"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batiments_classe",
                to="bati.nomenclature",
                verbose_name="Classe architecturale",
            ),
        ),
        migrations.AlterField(
            model_name="bati",
            name="proprietaire",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Propriétaire"
            ),
        ),
    ]
