# Generated by Django 5.2.7 on 2025-10-23 13:07

from django.db import migrations


def _migrate(apps, schema_editor):
    Nomenclature = apps.get_model("bati", "Nomenclature")
    NomenclatureType = apps.get_model("bati", "NomenclatureType")
    nomenclature_type_proprio = NomenclatureType(
        label="Type de propriétaire",
        definition="Type de propriétaire d'un bâtiment",
        code="TYPE_PROPRIO",
    )
    nomenclature_type_proprio.save()

    nomenclature_values = [
        Nomenclature(
            id_type=nomenclature_type_proprio,
            label="Commune",
            description="Bâtiment appartenant à une commune",
        ),
        Nomenclature(
            id_type=nomenclature_type_proprio,
            label="Privé",
            description="Bâtiment appartenant à un privé",
        ),
        Nomenclature(
            id_type=nomenclature_type_proprio,
            label="Association",
            description="Bâtiment appartenant à une association",
        ),
    ]
    Nomenclature.objects.bulk_create(nomenclature_values)


def _reverse(apps, schema_editor):
    NomenclatureType = apps.get_model("bati", "NomenclatureType")
    NomenclatureType.objects.filter(code="TYPE_PROPRIO").delete()

class Migration(migrations.Migration):

    dependencies = [
        ("bati", "0004_bati_periode_utilisation_bati_surface_and_more"),
    ]

    operations = [
        migrations.RunPython(_migrate, _reverse),
    ]
