# Generated by Django 5.2.1 on 2025-06-11 06:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0004_cadastre_patrimonialite_proprietaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('codecanton', models.AutoField(primary_key=True, serialize=False)),
                ('canton', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ClasseArchitecturale',
            fields=[
                ('codeclasse', models.AutoField(primary_key=True, serialize=False)),
                ('classe', models.CharField(max_length=100)),
                ('classe_decrite', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeConservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conservation', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Exposition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exposition', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Faitage',
            fields=[
                ('codefaitage', models.AutoField(primary_key=True, serialize=False)),
                ('faitage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Implantation',
            fields=[
                ('codepem', models.AutoField(primary_key=True, serialize=False)),
                ('pem', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Notepatri',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notepatri', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('codesecteur', models.AutoField(primary_key=True, serialize=False)),
                ('secteur', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='bati',
            name='cadastre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bati',
            name='patrimonialite',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bati',
            name='proprietaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='bati',
            name='name',
        ),
        migrations.AddField(
            model_name='bati',
            name='ancien_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bati',
            name='appelation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bati',
            name='bat_suppr',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='bati',
            name='capacite',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bati',
            name='date_insert',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='bati',
            name='date_update',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='bati',
            name='denivelle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bati',
            name='indivision',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='bati',
            name='info_masque',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bati',
            name='info_risquenat',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bati',
            name='lieu_dit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bati',
            name='pente',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bati',
            name='remarque',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bati',
            name='valide',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bati',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='bati',
            name='codeclasse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bati.classearchitecturale'),
        ),
        migrations.AddField(
            model_name='bati',
            name='codeconservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bati.codeconservation'),
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('codeinsee', models.AutoField(primary_key=True, serialize=False)),
                ('commune', models.CharField(max_length=100)),
                ('codecanton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bati.canton')),
                ('codesecteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bati.secteur')),
            ],
        ),
        migrations.AddField(
            model_name='bati',
            name='codeinsee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bati.commune'),
        ),
        migrations.AddField(
            model_name='bati',
            name='exposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bati.exposition'),
        ),
        migrations.AddField(
            model_name='bati',
            name='codefaitage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bati.faitage'),
        ),
        migrations.AddField(
            model_name='bati',
            name='codepem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bati.implantation'),
        ),
        migrations.AddField(
            model_name='bati',
            name='notepatri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bati.notepatri'),
        ),
        migrations.DeleteModel(
            name='Cadastre',
        ),
        migrations.DeleteModel(
            name='Patrimonialite',
        ),
        migrations.DeleteModel(
            name='Proprietaire',
        ),
    ]
