# Generated by Django 5.2.1 on 2025-06-11 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0005_canton_classearchitecturale_codeconservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id_nomenclature', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ref_nomenclatures"."t_nomenclatures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NomenclatureType',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('definition', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ref_nomenclatures"."bib_nomenclatures_types',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='commune',
            name='codecanton',
        ),
        migrations.RemoveField(
            model_name='bati',
            name='codeclasse',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='codesecteur',
        ),
        migrations.RemoveField(
            model_name='bati',
            name='codeinsee',
        ),
        migrations.RemoveField(
            model_name='bati',
            name='codepem',
        ),
        migrations.RemoveField(
            model_name='bati',
            name='notepatri',
        ),
        migrations.AlterField(
            model_name='bati',
            name='codeconservation',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__label': 'conservation'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_conservation', to='bati.nomenclature'),
        ),
        migrations.AlterField(
            model_name='bati',
            name='codefaitage',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__label': 'faitage'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_faitage', to='bati.nomenclature'),
        ),
        migrations.AlterField(
            model_name='bati',
            name='exposition',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__label': 'exposition'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_exposition', to='bati.nomenclature'),
        ),
        migrations.DeleteModel(
            name='Canton',
        ),
        migrations.DeleteModel(
            name='ClasseArchitecturale',
        ),
        migrations.DeleteModel(
            name='Secteur',
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='Implantation',
        ),
        migrations.DeleteModel(
            name='Notepatri',
        ),
        migrations.DeleteModel(
            name='CodeConservation',
        ),
        migrations.DeleteModel(
            name='Faitage',
        ),
        migrations.DeleteModel(
            name='Exposition',
        ),
    ]
