# Generated by Django 5.2.7 on 2025-10-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bati", "0005_auto_20251023_1307"),
    ]

    operations = [
        migrations.AddField(
            model_name="bati",
            name="comment_proprio",
            field=models.TextField(
                blank=True, null=True, verbose_name="Commenataire propriétaire"
            ),
        ),
        migrations.AlterField(
            model_name="bati",
            name="situation_geo",
            field=models.TextField(
                blank=True, null=True, verbose_name="Situation géographique"
            ),
        ),
    ]
