# Generated by Django 5.2.7 on 2025-10-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bati", "0006_bati_comment_proprio_alter_bati_situation_geo"),
    ]

    operations = [
        migrations.AddField(
            model_name="bati",
            name="annee_construction",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Année de construction"
            ),
        ),
        migrations.AlterField(
            model_name="bati",
            name="appelation",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="bati",
            name="notepatri",
            field=models.ForeignKey(
                limit_choices_to={"id_type__code": "NOTE_PAT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batiments_notepatri",
                to="bati.nomenclature",
                verbose_name="Note patrimoniale",
            ),
        ),
        migrations.AlterField(
            model_name="bati",
            name="perspectives",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"id_type__code": "PERSP"},
                null=True,
                through="bati.Perspective",
                to="bati.nomenclature",
            ),
        ),
        migrations.AlterField(
            model_name="bati",
            name="remarque_risque",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Remarque sur les risques naturels",
            ),
        ),
        migrations.AlterField(
            model_name="bati",
            name="risques_nat",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"id_type__code": "RISQUE"},
                related_name="batiments_risquenat",
                to="bati.nomenclature",
                verbose_name="Risques naturels",
            ),
        ),
        migrations.AlterField(
            model_name="bati",
            name="type_prioprietaire",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"id_type__code": "TYPE_PROPRIO"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_proprietaire",
                to="bati.nomenclature",
                verbose_name="Type de propriétaire",
            ),
        ),
    ]
