# Generated by Django 5.2.1 on 2025-06-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0006_nomenclature_nomenclaturetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bati',
            name='codepem',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__label': 'codepem'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_codepem', to='bati.nomenclature'),
        ),
        migrations.AddField(
            model_name='bati',
            name='notepatri',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__label': 'notepatri'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_notepatri', to='bati.nomenclature'),
        ),
    ]
