# Generated by Django 5.2.7 on 2025-10-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bati", "0007_bati_annee_construction_alter_bati_appelation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="travaux",
            name="agence_archi",
            field=models.CharField(
                blank=True, null=True, verbose_name="Agence d'architecture"
            ),
        ),
        migrations.AddField(
            model_name="travaux",
            name="entreprises",
            field=models.CharField(blank=True, null=True, verbose_name="Entreprises"),
        ),
    ]
