# Generated by Django 5.2.17 on 2026-09-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0008_travaux_agence_archi_travaux_entreprises'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bati',
            options={'permissions': (('read_bati', 'Can read bati'),)},
        ),
    ]
