# Generated by Django 5.2.1 on 2025-06-11 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0008_alter_bati_codepem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bati',
            name='notepatri',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__label': 'note_patri'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_notepatri', to='bati.nomenclature'),
        ),
    ]
