# Generated by Django 5.2.1 on 2025-06-11 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0009_alter_bati_notepatri'),
    ]

    operations = [
        migrations.AddField(
            model_name='bati',
            name='code_classe',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__label': 'classe_archi'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_classe', to='bati.nomenclature'),
        ),
    ]
