# Generated by Django 5.2.1 on 2025-06-11 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0010_bati_code_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='bati',
            name='secteur',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__label': 'secteur'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_secteur', to='bati.nomenclature'),
        ),
    ]
