# Generated by Django 5.2.1 on 2025-06-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0011_bati_secteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='bati',
            name='protection',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__label': 'protection'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_protection', to='bati.nomenclature'),
        ),
    ]
