# Generated by Django 5.2.1 on 2025-06-12 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0012_bati_protection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bati',
            name='info_masque',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__label': 'info_masque'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_info_masque', to='bati.nomenclature'),
        ),
    ]
