# Generated by Django 5.2.1 on 2025-06-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0013_alter_bati_info_masque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bati',
            name='info_masque',
        ),
        migrations.AddField(
            model_name='bati',
            name='commentaire',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
