# Generated by Django 5.2.1 on 2025-06-12 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0014_remove_bati_info_masque_bati_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='bati',
            name='masques',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__label': 'masque'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_info_masque', to='bati.nomenclature'),
        ),
    ]
