# Generated by Django 5.2.1 on 2025-06-12 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0015_bati_masques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bati',
            name='info_risquenat',
        ),
        migrations.AddField(
            model_name='bati',
            name='risquenat',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__label': 'risquenat'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_risquenat', to='bati.nomenclature'),
        ),
    ]
