# Generated by Django 5.2.1 on 2025-06-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0016_remove_bati_info_risquenat_bati_risquenat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bati',
            old_name='commentaire',
            new_name='commentaire_masque',
        ),
        migrations.RenameField(
            model_name='bati',
            old_name='remarque',
            new_name='remarque_risque',
        ),
    ]
