# Generated by Django 5.2.1 on 2025-06-13 08:04

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0017_rename_commentaire_bati_commentaire_masque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatiStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100, unique=True)),
                ('color', colorfield.fields.ColorField(default='#444444', image_field=None, max_length=25, samples=None, verbose_name='Color')),
            ],
        ),
        migrations.AddField(
            model_name='bati',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batiments_status', to='bati.batistatus'),
        ),
    ]
