# Generated by Django 5.2.1 on 2025-06-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0018_batistatus_bati_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bati',
            name='status',
        ),
        migrations.DeleteModel(
            name='BatiStatus',
        ),
    ]
