# Generated by Django 5.2.1 on 2025-06-17 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0019_remove_bati_status_delete_batistatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bati',
            name='code_classe',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__code': 'CL_ARCHI'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_classe', to='bati.nomenclature'),
        ),
        migrations.AlterField(
            model_name='bati',
            name='codeconservation',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__code': 'CONSERVATION'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_conservation', to='bati.nomenclature'),
        ),
        migrations.AlterField(
            model_name='bati',
            name='codefaitage',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__code': 'FAITAGE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_faitage', to='bati.nomenclature'),
        ),
        migrations.AlterField(
            model_name='bati',
            name='codepem',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__code': 'IMPLA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_codepem', to='bati.nomenclature'),
        ),
        migrations.AlterField(
            model_name='bati',
            name='exposition',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__code': 'EXPO'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_exposition', to='bati.nomenclature'),
        ),
        migrations.AlterField(
            model_name='bati',
            name='masques',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__code': 'MASQUE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_info_masque', to='bati.nomenclature'),
        ),
        migrations.AlterField(
            model_name='bati',
            name='notepatri',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__code': 'NOTE_PAT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_notepatri', to='bati.nomenclature'),
        ),
        migrations.AlterField(
            model_name='bati',
            name='protection',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__code': 'PROT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_protection', to='bati.nomenclature'),
        ),
        migrations.AlterField(
            model_name='bati',
            name='risquenat',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__code': 'RISQUE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_risquenat', to='bati.nomenclature'),
        ),
        migrations.AlterField(
            model_name='bati',
            name='secteur',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_type__code': 'SECTEUR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_secteur', to='bati.nomenclature'),
        ),
    ]
