# Generated by Django 5.2.1 on 2025-06-18 07:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0020_alter_bati_code_classe_alter_bati_codeconservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquetes',
            fields=[
                ('idenquete', models.AutoField(primary_key=True, serialize=False)),
                ('date_enquete', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_redaction', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_bat', models.ForeignKey(db_column='id_bat', on_delete=django.db.models.deletion.CASCADE, related_name='batiments_id_bat', to='bati.bati')),
                ('personne', models.ForeignKey(blank=True, limit_choices_to={'id_type__code': 'PERSONNES'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiments_personnes_enquetes', to='bati.nomenclature')),
            ],
        ),
    ]
