# Generated by Django 5.2.1 on 2025-06-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0021_enquetes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bati',
            old_name='code_classe',
            new_name='classe',
        ),
        migrations.RenameField(
            model_name='bati',
            old_name='codeconservation',
            new_name='conservation',
        ),
        migrations.RenameField(
            model_name='bati',
            old_name='codefaitage',
            new_name='faitage',
        ),
        migrations.RenameField(
            model_name='bati',
            old_name='codepem',
            new_name='implantation',
        ),
    ]
