# Generated by Django 5.2.1 on 2025-07-30 07:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaType",
            fields=[
                ("id_type", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_column="type_name", verbose_name=200)),
                ("code", models.CharField(db_column="type_code", verbose_name=50)),
                ("desc", models.TextField(db_column="type_desc")),
                ("ref_name", models.CharField(verbose_name=200)),
                ("ref_version", models.IntegerField()),
                ("num_version", models.CharField(verbose_name=50)),
                ("size_hierarchy", models.IntegerField()),
            ],
            options={
                "db_table": "bib_areas_types",
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id_area", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_column="area_name", verbose_name=250)),
                ("code", models.CharField(db_column="area_code", verbose_name=25)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=2154),
                ),
                ("centroid", django.contrib.gis.db.models.fields.PointField(srid=2154)),
                ("source", models.CharField(verbose_name=255)),
                ("comment", models.TextField()),
                ("enable", models.BooleanField()),
                (
                    "geom_4326",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "type",
                    models.ForeignKey(
                        db_column="id_type",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zoning.areatype",
                    ),
                ),
            ],
            options={
                "db_table": "l_areas",
            },
        ),
    ]
