# Generated by Django 5.2.1 on 2025-05-15 13:05

import django.db.models.deletion
import embed_video.fields
import paperclip.models
import paperclip.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=128, verbose_name="File type")),
            ],
            options={
                "verbose_name": "File type",
                "verbose_name_plural": "File types",
                "ordering": ["type"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="License name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment license",
                "verbose_name_plural": "Attachment licenses",
                "ordering": ["label"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "attachment_file",
                    models.FileField(
                        blank=True,
                        max_length=512,
                        upload_to=paperclip.models.attachment_upload,
                        validators=[paperclip.validators.FileMimetypeValidator()],
                        verbose_name="File",
                    ),
                ),
                (
                    "attachment_video",
                    embed_video.fields.EmbedVideoField(
                        blank=True, verbose_name="Video URL"
                    ),
                ),
                (
                    "attachment_link",
                    models.URLField(blank=True, verbose_name="Picture URL"),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Original creator",
                        max_length=128,
                        verbose_name="Author",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Renames the file",
                        max_length=128,
                        verbose_name="Filename",
                    ),
                ),
                (
                    "legend",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Details displayed",
                        max_length=128,
                        verbose_name="Legend",
                    ),
                ),
                (
                    "starred",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as starred",
                        verbose_name="Starred",
                    ),
                ),
                (
                    "is_image",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        help_text="Is an image file",
                        verbose_name="Is image",
                    ),
                ),
                (
                    "date_insert",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Insertion date"
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "random_suffix",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="User that uploaded",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "filetype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mapentitycommon.filetype",
                        verbose_name="File type",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mapentitycommon.license",
                        verbose_name="License",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "ordering": ["-date_insert"],
                "permissions": (
                    ("add_attachment", "Can add attachments"),
                    ("change_attachment", "Can change attachments"),
                    ("delete_attachment", "Can delete attachments"),
                    ("read_attachment", "Can read attachments"),
                    ("delete_attachment_others", "Can delete others' attachments"),
                ),
                "abstract": False,
                "default_permissions": (),
            },
        ),
    ]
